import { Geist, Geist_Mono, Poppins } from "next/font/google";
import localFont from 'next/font/local'

import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const poppins = Poppins({
  weight:["100","200","400","600"]
})
export const fontBangla = localFont({
  src:"./../fonts/mayaboti-normal.ttf"
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <header className="md:w-11/12 mx-auto py-6">
          <Navbar></Navbar>
        </header>
        <main className="md:w-11/12 mx-auto py-6 min-h-[calc(100vh-302px)]">
          {children}
        </main>
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
